[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#c0282d"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f4f7f9"
textColor = "#2c3e50"

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true
